version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "automated pr"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group updates to reduce PR spam
    groups:
      microsoft-dependencies:
        patterns:
          - "Microsoft.*"
      test-dependencies:
        patterns:
          - "xunit*"
          - "Moq"
          - "bunit*"
          - "NSubstitute"
          - "coverlet*"
          - "FluentAssertions"
          - "Shouldly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated pr"
      - "github-actions"