blank_issues_enabled: false
contact_links:
  - name: Osirion.Blazor Documentation
    url: https://github.com/obrana-boranija/Osirion.Blazor/blob/master/README.md
    about: Check our documentation before creating an issue
  - name: Discussions
    url: https://github.com/obrana-boranija/Osirion.Blazor/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: https://github.com/obrana-boranija/Osirion.Blazor/security/policy
    about: Please report security vulnerabilities here