name: Documentation check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-docs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run component docs checker
        shell: pwsh
        run: |
          pwsh -NoProfile -ExecutionPolicy Bypass -File .\tools\check_component_docs.ps1
          $report = .\tools\missing_component_docs.json
          if (-not (Test-Path $report)) { Write-Error "Missing report file"; exit 1 }
          $items = Get-Content $report -Raw | ConvertFrom-Json
          # filter out _Imports entries
          $missing = $items | Where-Object { $_.Component -notlike '_*' }
          if ($missing.Count -gt 0) {
            Write-Host "Undocumented components found:"; $missing | Format-Table -AutoSize
            Exit 1
          }
          Write-Host "All components documented"
