name: Performance Benchmarks

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**/*.cs'
      - 'src/**/*.razor'
      - 'benchmarks/**'
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore benchmarks/Osirion.Blazor.Benchmarks/Osirion.Blazor.Benchmarks.csproj
    
    - name: Build
      run: dotnet build --no-restore --configuration Release benchmarks/Osirion.Blazor.Benchmarks/Osirion.Blazor.Benchmarks.csproj
    
    - name: Run benchmarks
      run: dotnet run --project benchmarks/Osirion.Blazor.Benchmarks/Osirion.Blazor.Benchmarks.csproj --configuration Release -- --filter "*" --exportJson benchmark-results.json
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results.json
        retention-days: 90
    
    - name: Display benchmark results
      run: |
        echo "Benchmark Results Summary:"
        cat benchmark-results.json | jq -r '.Benchmarks[] | "\(.Method): \(.Mean) \(.MeanUnit)"'
        
    # Optional: Compare with previous benchmark results
    - name: Compare with previous benchmarks
      run: |
        if [ -f "benchmark-history/latest.json" ]; then
          echo "Comparing with previous benchmark results..."
          # Add comparison logic here
        else
          echo "No previous benchmark results found for comparison"
        fi