name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 2.0.1)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Update version in project files
        run: |
          # Track if any files were changed
          changed=0

          # Update version in all Osirion.Blazor module projects
          for file in $(find ./src -name "*.csproj"); do
            # Use grep to check the current version
            current_version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' "$file")
            
            if [ "$current_version" != "${{ github.event.inputs.version }}" ]; then
              sed -i "s/<Version>.*<\/Version>/<Version>${{ github.event.inputs.version }}<\/Version>/" "$file"
              echo "Updated version in $file"
              changed=$((changed + 1))
            fi
          done

          # Update CHANGELOG.md
          TODAY=$(date +%Y-%m-%d)
          sed -i "0,/## \[Unreleased\]/s/## \[Unreleased\]/## [Unreleased]\n\n## [${{ github.event.inputs.version }}] - $TODAY/" CHANGELOG.md
          
          # Check if CHANGELOG was modified
          if git diff --quiet CHANGELOG.md; then
            echo "CHANGELOG.md was not modified"
          else
            changed=$((changed + 1))
          fi

          # Exit with an error if no changes were made
          if [ $changed -eq 0 ]; then
            echo "No changes were detected. Ensure the version is different from the current one."
            exit 1
          fi

      - name: Ensure Labels Exist
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/labels \
          -d '{"name": "release", "color": "f29513"}' || echo "Label 'release' already exists."
          
          curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/labels \
          -d '{"name": "automated pr", "color": "0e8a16"}' || echo "Label 'automated pr' already exists."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Prepare release ${{ github.event.inputs.version }}"
          branch: "release/${{ github.event.inputs.version }}"
          delete-branch: true
          title: "Release ${{ github.event.inputs.version }}"
          body: |
            Automated PR to prepare release ${{ github.event.inputs.version }}
            
            ## Changes
            - Updated version numbers to ${{ github.event.inputs.version }}
            - Updated CHANGELOG.md
            
            Please review the changes and merge if everything looks correct.
          labels: |
            release
            automated pr
