name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 2.0.1)'
        required: true
        type: string

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Update version in project files
        run: |
          find . -name "*.csproj" -type f -exec sed -i "s/<Version>[0-9]\+\.[0-9]\+\.[0-9]\+<\/Version>/<Version>${{ github.event.inputs.version }}<\/Version>/g" {} \;

      - name: Update CHANGELOG.md
        run: |
          TODAY=$(date +%Y-%m-%d)
          sed -i "0,/## \[Unreleased\]/s/## \[Unreleased\]/## [Unreleased]\n\n## [${{ github.event.inputs.version }}] - $TODAY/" CHANGELOG.md

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          BRANCH="release/${{ github.event.inputs.version }}"
          git checkout -b $BRANCH
          
          git add -A
          git commit -m "Prepare release ${{ github.event.inputs.version }}"
          
          git push origin $BRANCH
          
          gh pr create \
            --title "Release ${{ github.event.inputs.version }}" \
            --body "Automated PR to prepare release ${{ github.event.inputs.version }}" \
            --base master \
            --head $BRANCH